version: '3'
services:
  app:
    restart: always
    build: .
    depends_on:
      - db
      - redis
    ports:
      - 5000:5000
    expose:
      - 5000
    env_file:
      -  .env
    environment:
      - MONGODB_HOST=db
      - REDIS_HOST=redis

  db:
    restart: always
    image: bitnami/mongodb
    env_file:
      - .env
    volumes:
      - db-data:/bitnami/mongodb
    ports:
      - 27017:27017
    expose:
      - 27017

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  db-data:
