version: '3'
services:
  app:
    restart: always
    build: .
    depends_on:
      - db
      - redis
    ports:
      - 5000:5000
    env_file:
      -  .env
    environment:
      - MONGODB_HOST=db
      - REDIS_HOST=redis
    command: uvicorn app.main:app --workers 2 --host "0.0.0.0" --port 5000

  db:
    restart: always
    image: bitnami/mongodb
    env_file:
      - .env
    volumes:
      - db-data:/bitnami/mongodb
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  q1_worker:
    restart: always
    build: .
    depends_on:
      - redis
    environment:
      - MONGODB_HOST=db
      - REDIS_HOST=redis
    command: python runworker.py app.settings.Q1_SETTINGS

volumes:
  redis-data:
  db-data:
