name: "Deploy App"

on:
  push:
    branches:
      - main

env:
  GITHUB_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image (app)
        env:
          IMAGE_NAME: ${{ env.GITHUB_REGISTRY }}/${{ github.repository }}:latest
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          docker push ${{ env.IMAGE_NAME }}

  deploy:
    runs-on: getpay-runner
    needs: build
    environment: getpay-api
    steps:
      -   uses: actions/checkout@v2
      -   name: Deployment
          run: |
            echo 'Hello World!'
