name: Unit testing

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next

jobs:
  test_job:
    name: Run tests using python v${{ matrix.py }}
    runs-on: ubuntu-latest
    environment: getpay-api
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.9"
          - "3.8"

    env:
      REDIS_HOST: redis
      MONGODB_USERNAME: test_user
      MONGODB_PASSWORD: test123456
      MONGODB_DATABASE: test_gpdb
      MONGODB_HOST: db

    container: python:${{ matrix.py }}
    services:
      db:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ env.MONGODB_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ env.MONGODB_PASSWORD }}
          MONGO_INITDB_DATABASE: ${{ env.MONGODB_DATABASE }}
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Create environment file
        run: printf '${{secrets.ENV_FILE}}' >> .env

      - name: Export environment variables (testing .env)
        uses: cardinalby/export-env-action@1.0.0
        with:
          envFile: .env.testing

      - name: Install dependencies
        run: |
          pip install -r all-requirements.txt

      - name: Initialize data
        run: |
          python3 manage.py init
          python3 manage.py create_user -u ${{env.USER_EMAIL}} -p ${{env.USER_PASSWORD}} -y

      - name: Run tests
        run: |
          pytest -v --cache-clear
