name: Unit testing

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next

jobs:
  test_job:
    name: Run tests using python v${{ matrix.py }}
    runs-on: ubuntu-latest
    environment: getpay-api
    strategy:
      fail-fast: false
      matrix:
        py:
          - "3.9"
          - "3.8"

    env:
      MONGODB_USERNAME: gpuser
      MONGODB_PASSWORD: gppassword
      MONGODB_DATABASE: gpdatabase
      MONGODB_URL: mongodb://gpuser:gppassword@localhost:27017/gpdatabase?authSource=admin

    steps:
      - uses: actions/checkout@v3
      - name: Setup python v${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Create environment file
        run: printf '${{secrets.ENV_FILE}}' > .env

      - name: Export environment variables (testing .env)
        uses: cardinalby/export-env-action@1.0.0
        with:
          envFile: .env.testing

      - name: Setup redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: latest

      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: 5.0
          mongodb-username: ${{env.MONGODB_USERNAME}}
          mongodb-password: ${{env.MONGODB_PASSWORD}}
          mongodb-db: ${{env.MONGODB_DATABASE}}

      - name: Install dependencies
        run: |
          pip install -r all-requirements.txt

      - name: Initialize data
        run: |
          python3 manage.py init
          python3 manage.py create_user -u ${{env.USER_EMAIL}} -p ${{env.USER_PASSWORD}} -y

      - name: Run tests
        run: |
          pytest -sv --cache-clear

      - name: Cleanup Database
        run: |
          python3 manage.py drop_collection -f
